version: '3'
services:
  snarkon:
    build: ./
    ports:
      - 80:80
    volumes:
      # - ./:/app
      - ~/.aws:/root/.aws
      # - nginx logs
    environment:
      - AWS_S3_BUCKET=nld-datalab
      - SQLITE_DB=db.sqlite
    privileged: true