version: '3'
services:
  bucketview:
    build: ./
    volumes:
      - ./app:/app
      - ~/.aws:/root/.aws
    ports:
      - 8569:80
    privileged: true
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'   
      - AWS_S3_BUCKET=nld-realignment 
      - SQLITE_DB=db.sqlite
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
    networks:
      - outside

networks:
  outside:
    external:
      name: terrastitch_terranet