version: '3'
services:
  bucketview:
    build: ./
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - ~/.aws:/root/.aws
      - ./logs:/var/log/nginx
      - ./custom.conf:/etc/nginx/conf.d/custom.conf
    environment:
      - AWS_S3_BUCKET=nld-datalab
      - SQLITE_DB=db.sqlite
    privileged: true