version: '3'
services:
  snarkon:
    build: ./
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - ~/.aws:/root/.aws
      - ./logs:/var/log/nginx
    environment:
      - AWS_S3_BUCKET=nld-datalab
      - SQLITE_DB=db.sqlite
    privileged: true